image: node:20-alpine

variables:
  NODE_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - npm test

test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  stage: deploy
  script:
    - npm test
  artifacts:
    paths:
      - public
  only:
    - production
